# fly.toml file generated for devopsdockeruh-coursepage on 2023-05-11T10:38:18+02:00

app = "devopsdockeruh-coursepage"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "waw"
processes = []

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
  
[build]
  image = "devopsdockeruh/coursepage"
