version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: db_redmine
    volumes:
      - database:/var/lib/postgres/database

  redmine:
    image: redmine:5.0-alpine
    environment:
      - REDMINE_DB_POSTGRES=db
      - REDMINE_DB_PASSWORD=example
    ports:
      - 9999:3000
    volumes:
      - files:/usr/src/redmine/files
    depends_on:
      - db

  adminer: 
    image: adminer:4
    restart: always
    environment:
      - ADMINER_DESIGN=galkaev
      # - ADMINER_DEFAULT_SERVER=db
    ports: 
      - 8083:8080

volumes:
  database:
  files:
