version: '3.8'

services:

  example-backend:
    build: ./Backend
    image: example-backend:1.14
    ports:
      - 8000:8000
    volumes:
      - ./text.log:/usr/app/text.log
  
  example-frontend:
    build: ./Frontend
    image: example-frontend:1.14
    ports:
      - 5000:5000 
