# By default our devopsdockeruh/simple-web-service:alpine doesn't have a CMD. It instead uses ENTRYPOINT to declare which application is run
FROM devopsdockeruh/simple-web-service:alpine
# start server
CMD server